config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root 'home#index'
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)


  resources :products, only: %i(index show new create) do
    collection do
      get 'search'
    end  
  
    scope module: :products do
      resources :add_to_baskets, only: %i(create) 
      resources :delete_in_baskets, only: %i(create)
    end
  end
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create)
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products

  # def total_price
  #   total_jpy_price + total_usd_price
  # end
  
  def total_price
    jp_products = products.all
    jp_products.sum(:price)
  end


end

app/models/basket_product.rb
class BasketProduct < ApplicationRecord
  belongs_to :basket
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :thumbnail, ThumbnailUploader
  acts_as_taggable
  has_many :basket_products, dependent: :destroy
  has_many :purchase_records, dependent: :destroy


  validates :name, presence: true 
  validates :description, presence: true
  validates :explanation, presence: true
  validates :price, presence: true

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%").order(created_at: :desc)
  end

end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :user
  has_many :purchase_record_products, dependent: :destroy
  has_many :products, through: :purchase_record_products
end

app/models/purchase_record_product.rb
class PurchaseRecordProduct < ApplicationRecord
  belongs_to :product
  belongs_to :purchase_record
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :basket, dependent: :destroy
  has_one :purchase_record, dependent: :destroy

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  before_action :authenticate_admin!
  
  def new
    @product = current_admin.products.build
  end

  def create
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to root_path, notice: '作成に成功'
    else
      flash[:error] = '作成に失敗'
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :unit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :first_name_furigana, :last_name, :last_name_furigana] )
  end
  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      root_path
    elsif resource.is_a?(Admin)
      admins_root_path
    end
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!
  def show
    basket = current_user.basket
    @products = basket.products
    @total_price = basket.total_price
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    token = params[:stripeToken]
    product_ids = params[:product_ids].map(&:to_i)

    products = current_user.basket.products.where(id: product_ids)
    total = products.sum(:price)

    basket_products = current_user.basket.basket_products.where(product_id: product_ids)
    basket_products.each(&:destroy!)
    
    Stripe::Charge.create({
      amount: total,
      currency: 'jpy',
      description: 'Example charge',
      source: token
    })
    
    purchase_record = current_user.purchase_record || current_user.create_purchase_record
    ids = product_ids.map { |id| { product_id: id} }
    purchase_record.purchase_record_products.create!(ids)

    redirect_to products_path, notice: '決済に成功しました'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    records = PurchaseRecordProduct.all.limit(6).pluck(:product_id)
    @products = Product.where id:records
  end
end

app/controllers/products/add_to_baskets_controller.rb
class Products::AddToBasketsController < Products::ApplicationController
  def create
    basket = current_user.basket || current_user.create_basket
    product = Product.find(params[:product_id])
    basket.basket_products.create!(product_id: product.id)

    redirect_to basket_path
  end
end

app/controllers/products/application_controller.rb
class Products::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/products/delete_in_baskets_controller.rb
class Products::DeleteInBasketsController < Products::ApplicationController
  def create
    basket = current_user.basket
    product = Product.find(params[:product_id])

    basket_product = basket.basket_products.find_by(product_id: product.id)
    basket_product.destroy!

    redirect_to basket_path

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.order(created_at: :desc).limit(12)

  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      flash[:error] = '作成に失敗'
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    if user_signed_in?
      @current_user_record = PurchaseRecordProduct.where(purchase_record: current_user.id).pluck(:product_id)
    end
  end

  def search
    @products = Product.all.order(created_at: :desc).limit(12)
    @search_products = Product.search(params[:keyword])
    
  end
 


  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :explanation, :tag_list, :thumbnail).merge(seller_id: current_user.id, nickname: current_user.nickname)
  end
end

app/helpers/add_to_baskets_helper.rb
module AddToBasketsHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/delete_in_baskets_helper.rb
module DeleteInBasketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        hard_wrap: true
      }
      extensions = {
        no_intra_emphasis: true,
        tables: true,
        fenced_code_blocks: true,
        autolink: true,
        quote: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.haml
= render "/layouts/header"

.container
  .search
    = form_tag(search_products_path, :method => "get") do
      = text_field_tag :keyword, '',class:"search_field",placeholder:"気になるキーワードを検索"
      = submit_tag "検索",class:"search_button"
  %span.title
    記事一覧
  .products
    - @products.each do |product|
      .col-xs-6.col-md-3
        = link_to product_path(product.id), class:"product-link" do
          .box
            .thumbnail
              = image_tag product.thumbnail,class:"product-image"
            .product-title
              = product.name
            .info
              %span.name
                = product.nickname
              %span.date
                = product.created_at.strftime("%Y年%m月%d日")
            .explanation
              = product.explanation
            .price
              = "#{product.price}円"
  
= render "/layouts/footer"

app/views/products/new.html.haml
= render "/layouts/header"



%h2.text-center
  商品記事の投稿
.container
  .new-product
    = simple_form_for @product do |f|
      = f.input :name,label:"商品記事名",placeholder:"記事名を入力"
      %p.sub-title
        サムネイル画像選択
      = f.file_field :thumbnail, class:"thumbnail-field"
      %p.sub-title
        記事内容（無料記事）
      = f.text_area :explanation,{"data-uk-htmleditor" => "{markdown:true}",label:"aaa"}
      %p.sub-title
        記事内容（有料記事）
      = f.text_area :description,{"data-uk-htmleditor" => "{markdown:true}"}
      = f.input :tag_list, value: @product.tag_list.join(','),placeholder:"例: rails, php, 言語", label:"タグリスト"
      = f.input :price, label:"価格",placeholder:"価格を入力"
      .new-button
        = f.button :button,{name:'submit',value: '1',class: 'btn btn-primary'} do
          投稿する

= render "/layouts/footer"

app/views/products/search.html.haml
= render "/layouts/header"

.container
  .search
  = form_tag(search_products_path, :method => "get") do
    = text_field_tag :keyword, '',class:"search_field",placeholder:"気になるキーワードを検索"
    = submit_tag "検索",class:"search_button"

  - if @search_products.present?
    %span.title
      検索結果
    - @search_products.each do |product|
      .col-xs-6.col-md-3
        = link_to product_path(product.id), class:"product-link" do
          .box
            .thumbnail
              = image_tag product.thumbnail,class:"product-image"
            .product-title
              = product.name
            .info
              %span.name
                = product.nickname
              %span.date
                = product.created_at.strftime("%Y年%m月%d日")
            .explanation
              = product.explanation
            .price
              = "#{product.price}円"
  - else
    %span.title
      キーワードに該当するものがありません
    %span.title
      新着記事
    - @products.each do |product|
      .col-xs-6.col-md-3
        = link_to product_path(product.id), class:"product-link" do
          .box
            .thumbnail
              = image_tag product.thumbnail,class:"product-image"
            .product-title
              = product.name
            .info
              %span.name
                わたる
              %span.date
                = product.created_at.strftime("%Y年%m月%d日")
            .explanation
              = product.explanation
= render "/layouts/footer"

app/views/products/show.html.haml
= render "/layouts/header"

.container
  .product
    .product-top
      .product-title
        .date
          = @product.created_at.strftime("%Y年%m月%d日")
        .thumbnail
          = image_tag @product.thumbnail
        %h1.main-title
          = @product.name
        %span.tag
          - @product.tag_list.each do |tag|
            %span.badge= tag

    - if user_signed_in?
      - if @current_user_record.include?(@product.id) || @product.seller_id == current_user.id
        .main-content
          .explanation
            = markdown(@product.explanation)
        
          .description
            %p.next2
              [---ここから有料記事になります-----]
            = markdown(@product.description)
      - else
        .main-content
          .explanation
            = markdown(@product.explanation)
          .purchase-guide
            %p.next
              続きは購入後、ご覧頂けます   
            .button
              = link_to product_add_to_baskets_path(@product), method: :post do
                %button.btn.btn-primary.btn-lg{:type => "button"} 買い物かごに追加する 
    -else
      .main-content
        .explanation
          = markdown(@product.explanation)
        .purchase-guide
          %p.next
            続きは購入後、ご覧頂けます   
          .button
            = link_to product_add_to_baskets_path(@product), method: :post do
              %button.btn.btn-primary.btn-lg{:type => "button"} 買い物かごに追加する 
     


= render "/layouts/footer"