config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root 'home#index'
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)


  resources :products, only: %i(index show new create) do
    collection do
      get 'search'
    end  
  
    scope module: :products do
      resources :add_to_baskets, only: %i(create) 
      resources :delete_in_baskets, only: %i(create)
    end
  end
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create)
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products

  # def total_price
  #   total_jpy_price + total_usd_price
  # end
  
  def total_price
    jp_products = products.all
    jp_products.sum(:price)
  end


end

app/models/basket_product.rb
class BasketProduct < ApplicationRecord
  belongs_to :basket
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :thumbnail, ThumbnailUploader
  acts_as_taggable
  has_many :basket_products, dependent: :destroy
  has_many :purchase_records, dependent: :destroy


  validates :name, presence: true 
  validates :description, presence: true
  validates :explanation, presence: true
  validates :price, presence: true

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%").order(created_at: :desc)
  end

end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :user
  has_many :purchase_record_products, dependent: :destroy
  has_many :products, through: :purchase_record_products
end

app/models/purchase_record_product.rb
class PurchaseRecordProduct < ApplicationRecord
  belongs_to :product
  belongs_to :purchase_record
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :basket, dependent: :destroy
  has_one :purchase_record, dependent: :destroy

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!
  def show
    basket = current_user.basket
    @products = basket.products
    @total_price = basket.total_price
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    token = params[:stripeToken]
    product_ids = params[:product_ids].map(&:to_i)

    products = current_user.basket.products.where(id: product_ids)
    total = products.sum(:price)

    basket_products = current_user.basket.basket_products.where(product_id: product_ids)
    basket_products.each(&:destroy!)
    
    Stripe::Charge.create({
      amount: total,
      currency: 'jpy',
      description: 'Example charge',
      source: token
    })
    
    purchase_record = current_user.purchase_record || current_user.create_purchase_record
    ids = product_ids.map { |id| { product_id: id} }
    purchase_record.purchase_record_products.create!(ids)

    redirect_to products_path, notice: '決済に成功しました'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    records = PurchaseRecordProduct.all.limit(6).pluck(:product_id)
    @products = Product.where id:records
  end
end

app/helpers/add_to_baskets_helper.rb
module AddToBasketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        hard_wrap: true
      }
      extensions = {
        no_intra_emphasis: true,
        tables: true,
        fenced_code_blocks: true,
        autolink: true,
        quote: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.haml
%footer.footer-bs
  .row
    .col-md-3.footer-brand
      %h2 Bits of knowledge
      %p あなたの「知識」が誰かの「知らない」を無くす。
      %p 些細だと思っているあなたの知識が誰かを救うかも
    .col-md-4.footer-nav
      %h4 Menu
      .col-md-6
        %ul.pages
          %li
            %a{:href => "#"} ホーム
          %li
            %a{:href => "#"} 商品記事一覧
          %li
            %a{:href => "#"} 新規登録
          %li
            %a{:href => "#"} ログイン
      .col-md-6
        %ul.list
          %li
            %a{:href => "#"} About Us
          %li
            %a{:href => "#"} Contacts
          %li
            %a{:href => "#"} Terms  Condition
          %li
            %a{:href => "#"} Privacy Policy
    .col-md-2.footer-social
      %h4 Follow Us
      %ul
        %li
          %a{:href => "#"} Facebook
        %li
          %a{:href => "#"} Twitter
        %li
          %a{:href => "#"} Instagram
        %li
          %a{:href => "#"} RSS
    .col-md-3.footer-ns
      %h4 商品記事の検索
      %p 気になるキーワードを検索してみましょう
      %p
        .input-group
          = form_tag(search_products_path, :method => "get") do
            = text_field_tag :keyword, '',class:"search_field",placeholder:"キーワードを検索"
            = submit_tag "検索",class:"search_button"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand.active{:href => "/"} Bits of knowledge
    - if current_user.present?
      #navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            = link_to "ホーム", root_path

          %li.active
            = link_to "商品記事一覧", products_path

          %li.active
            = link_to "新規投稿", new_product_path
          
          %li.active
            = link_to "ログアウト", destroy_user_session_path, method: :delete
    - elsif current_admin.present?
      #navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "/"} ホーム
          %li= link_to "商品記事一覧", products_path          
          %li= link_to "ログアウト(アドミン）", destroy_admin_session_path, method: :delete
    - else
      #navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "/"} ホーム
          %li= link_to "商品記事一覧", products_path          
          %li= link_to "新規登録", new_user_registration_path, method: :get
          %li= link_to "ログイン", new_user_session_path, method: :get

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bits of knowledge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- UI Kit -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/js/uikit.min.js"></script>

    <!-- Codemirror and marked dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/codemirror.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/codemirror.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/markdown/markdown.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/addon/mode/overlay.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/xml/xml.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/gfm/gfm.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML editor CSS and JavaScript -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/css/components/htmleditor.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/js/components/htmleditor.js"></script>
  </head>
  <%# <div class="container"> %>
  <body>
    <%= yield %>
  </body>
  <%# </div> %>
</html>